#!/bin/bash
if [ $# -ne 1 ]; then
        # Print usage
        echo 'wrong!!! bad operator!!!
        usage:
        ./newpost $FILENAME_SAFE_SUBJECT
        e.g.
        ./newpost my-subject-without-spaces
        '
            exit 1
fi
NEWPOST=_posts/`date -I`-$1.md
TITLE=$(echo $1|sed "s/-/\ /g")
cp -n post-template $NEWPOST
sed -i "s/TITLE_REPLACEME/$TITLE/" $NEWPOST
echo "
you can now use your favorite editor to edit $NEWPOST
"
# kate $NEWPOST
vim $NEWPOST
