#!/bin/bash
if [ $# -ne 1 ]; then
        # Print usage
        echo 'wrong!!! bad operator!!!
        usage:
        ./newpost $FILENAME_SAFE_SUBJECT
        e.g.
        ./newpost my-subject-without-spaces
        '
            exit 1
fi
DRAFT=$1.md
DRAFT_NAME= $(echo $1|sed "s/_drafts//")
NEWPOST=_posts/`date -I`-$DRAFT_NAME.md
mv $DRAFT $NEWPOST
echo "
you can now use your favorite editor to edit $NEWPOST
"
# vim $NEWPOST
